services:
  - type: web
    name: apnadost-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_URL
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false 